name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with black, ruff, mypy
        run: |
          pip install black ruff mypy
          black --check .
          ruff .
          mypy .
      - name: Run tests
        run: |
          pytest
      - name: Build Docker image
        run: |
          docker build -t mcp-router-server .
      - name: Docker healthcheck
        run: |
          docker run -d -p 8000:8000 --name mcp-router-server mcp-router-server
          sleep 5
          curl --fail http://localhost:8000/health
          docker stop mcp-router-server
          docker rm mcp-router-server
